### ISSUE TITLE
Make Log() function in transaction package variadic 

### ISSUE THREAD

**Issue by jerrinsg** [vmware/go-pmem-transaction#7]
Currently the `Log()` function only takes one argument. Pratap suggested making this variadic. This would be beneficial in cases where we log variables one after the other.

E.g.:
```go
func main() {
	pmem.Init("database")
	var head *node
	n := pnew(node)

	head = (*node)(pmem.New(”hd", head))

	tx := transaction.NewUndoTx()
	tx.Begin()
	tx.Log(head)
	tx.Log(n)
	n.next = head.next
	head.next = n
	tx.End()
	transaction.Release(tx)
}
```

Here the two separate log statements could be combined as follows:

```go
	txLog(head, n)
```

**Comment by mohit10verma** [comment]
This issue is fixed with this [commit](https://github.com/vmware/go-pmem-transaction/commit/345b343294bdfba31cc15a6683de5d6bc942d82e). Closing.
